modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_full_name}"
credits="Credits go to the Bonsai Studios team"
authors="sunbatheproductions28"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${mc_version},1.21)"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"

[[dependencies.${mod_id}]]
modId="yungsapi"
versionRange="[${yungsapi_mc_version}-Forge-${yungsapi_version},)"
mandatory=true
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
versionRange="[${forge_geckolib_version},)"
mandatory=true
ordering="NONE"
side="BOTH"